/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApiClientsRouteImport } from './routes/_authenticated/api-clients'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedExtratosRouteImport } from './routes/_authenticated/extratos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedClientesCustomerIdRouteImport } from './routes/_authenticated/clientes.$customerId'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiClientsRoute = AuthenticatedApiClientsRouteImport.update({
  id: '/api-clients',
  path: '/api-clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExtratosRoute = AuthenticatedExtratosRouteImport.update({
  id: '/extratos',
  path: '/extratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesCustomerIdRoute =
  AuthenticatedClientesCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/api-clients': typeof AuthenticatedApiClientsRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/contas': typeof AuthenticatedContasRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/extratos': typeof AuthenticatedExtratosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/clientes/$customerId': typeof AuthenticatedClientesCustomerIdRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api-clients': typeof AuthenticatedApiClientsRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/contas': typeof AuthenticatedContasRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/extratos': typeof AuthenticatedExtratosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$customerId': typeof AuthenticatedClientesCustomerIdRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/api-clients': typeof AuthenticatedApiClientsRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/extratos': typeof AuthenticatedExtratosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$customerId': typeof AuthenticatedClientesCustomerIdRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-clients'
    | '/auditoria'
    | '/clientes'
    | '/contas'
    | '/docs'
    | '/extratos'
    | '/financeiro'
    | '/metas'
    | '/notificacoes'
    | '/pedidos'
    | '/planos'
    | '/produtos'
    | '/clientes/$customerId'
    | '/api/public/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api-clients'
    | '/auditoria'
    | '/clientes'
    | '/contas'
    | '/docs'
    | '/extratos'
    | '/financeiro'
    | '/metas'
    | '/notificacoes'
    | '/pedidos'
    | '/planos'
    | '/produtos'
    | '/'
    | '/clientes/$customerId'
    | '/api/public/orders'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/api-clients'
    | '/_authenticated/auditoria'
    | '/_authenticated/clientes'
    | '/_authenticated/contas'
    | '/_authenticated/docs'
    | '/_authenticated/extratos'
    | '/_authenticated/financeiro'
    | '/_authenticated/metas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pedidos'
    | '/_authenticated/planos'
    | '/_authenticated/produtos'
    | '/_authenticated/'
    | '/_authenticated/clientes/$customerId'
    | '/api/public/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-clients': {
      id: '/_authenticated/api-clients'
      path: '/api-clients'
      fullPath: '/api-clients'
      preLoaderRoute: typeof AuthenticatedApiClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extratos': {
      id: '/_authenticated/extratos'
      path: '/extratos'
      fullPath: '/extratos'
      preLoaderRoute: typeof AuthenticatedExtratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$customerId': {
      id: '/_authenticated/clientes/$customerId'
      path: '/$customerId'
      fullPath: '/clientes/$customerId'
      preLoaderRoute: typeof AuthenticatedClientesCustomerIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesCustomerIdRoute: typeof AuthenticatedClientesCustomerIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesCustomerIdRoute: AuthenticatedClientesCustomerIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApiClientsRoute: typeof AuthenticatedApiClientsRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedExtratosRoute: typeof AuthenticatedExtratosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApiClientsRoute: AuthenticatedApiClientsRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedExtratosRoute: AuthenticatedExtratosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
